FROM node:14-alpine3.10
LABEL version="1.0"
LABEL description="Development image for the safespace MERN API"
WORKDIR /app
# COPY ["package.json","package-lock.json*","npm-shrinkwrap.json*", "./"]
COPY /package*.json /app/
RUN npm install
COPY . .
EXPOSE 5000
CMD [ "npm", "run", "start" ]

